import Head from 'next/head';
import styles from 'styles/Home.module.css';
import MailIcon from '@mui/icons-material/Mail';
import InboxIcon from '@mui/icons-material/Inbox';

export default function Home() {
  return pug`
    Layout
      div(className=${styles.container})
        Head
          title Next App
          meta(name="description", content="Generated by create next app")
          link(rel="icon" href="/favicon.ico")
        div
          h2 Main Field
          Badge(badgeContent=${4} color="primary")
            MailIcon(color="action")
          List
            ListItem(disablePadding)
              ListItemButton
                ListItemIcon
                  InboxIcon
                ListItemText( primary="Inbox")
  `
}
